close all;clear all;clc;
%% DMD
a_1= load('SWEE_DMD_DMD_Q0.10_R0.01_inth0001_S2_L1.mat');
a_2= load('SWEE_DMD_DMD_Q0.10_R0.01_inth0001_S2_L5.mat');
a_3= load('SWEE_DMD_DMD_Q0.10_R0.01_inth0001_S2_L15.mat');
a_4= load('SWEE_DMD_DMD_Q0.10_R0.01_inth0001_S2_L20.mat');
a_5= load('SWE_DMD_DMD_Q0.10_R0.01_inth0001_S2_L30.mat');
%%
% a_1= load('Copy_of_SWE_DMD_DMD_Q0.10_R0.01_inth0001_S2_L5.mat');%48
% a_2= load('SWE_DMD_DMD_Q0.10_R0.01_inth0001_S2_L15.mat');%48
b_1=a_1.results;
c_1=a_1.params;
%%
b_2=a_2.results;
c_2=a_2.params;
%%
b_3=a_3.results;
c_3=a_3.params;
b_4=a_4.results;
c_4=a_4.params;
b_5=a_5.results;
c_5=a_5.params;
%%
PhysicalProjection=c_1.PhysicalProjection;
DataProjection=c_1.DataProjection;
epsQ=c_1.epsQ;
epsR=c_1.epsR;
numModes=c_1.numModes;
Num=c_1.Num;
Mult=c_1.Mult;
ESS_1=b_1.ESS;
ESS_2=b_2.ESS;
ESS_3=b_3.ESS;
ESS_4=b_4.ESS;
ESS_5=b_5.ESS;
Time=b_1.Time;
RMSEsave_1=b_1.RMSEsave;
RMSEsave_2=b_2.RMSEsave;
RMSEsave_3=b_3.RMSEsave;
RMSEsave_4=b_4.RMSEsave;
RMSEsave_5=b_5.RMSEsave;
RSpercent_1=b_1.ResampPercent;
RSpercent_2=b_2.ResampPercent;
RSpercent_3=b_3.ResampPercent;
RSpercent_4=b_4.ResampPercent;
RSpercent_5=b_5.ResampPercent;
%%
RSpercent_1 = mean(squeeze(RSpercent_1),[2]);
RSpercent_2 = mean(squeeze(RSpercent_2),[2]);
RSpercent_3 = mean(squeeze(RSpercent_3),[2]);
RSpercent_4 = mean(squeeze(RSpercent_4),[2]);
RSpercent_5 = mean(squeeze(RSpercent_5),[2]);
%%
for j=1:Num
    numModes(j)=j*Mult;
    ESSave_1(j) = mean(ESS_1(:,j,:), [1 3])/1;
    ESSave_2(j) = mean(ESS_2(:,j,:), [1 3])/5;
    ESSave_3(j) = mean(ESS_3(:,j,:), [1 3])/15;
    ESSave_4(j) = mean(ESS_3(:,j,:), [1 3])/20;
    ESSave_5(j) = mean(ESS_3(:,j,:), [1 3])/30;
    RMSEave_1(j) = mean(RMSEsave_1(:,j,:), [1 3]);
    RMSEave_2(j) = mean(RMSEsave_2(:,j,:), [1 3]);
    RMSEave_3(j) = mean(RMSEsave_3(:,j,:), [1 3]);
    RMSEave_4(j) = mean(RMSEsave_4(:,j,:), [1 3]);
    RMSEave_5(j) = mean(RMSEsave_5(:,j,:), [1 3]);
    %     ESSSD_1(j) = std(ESS_1(:,j,:), [1 3]);
    err_1(j) = std(reshape(squeeze(ESS_1(:,j,:)),[24*20,1]))/1;
    err_2(j) = std(reshape(squeeze(ESS_2(:,j,:)),[24*20,1]))/5;
    err_3(j) = std(reshape(squeeze(ESS_3(:,j,:)),[24*20,1]))/15;
    err_4(j) = std(reshape(squeeze(ESS_4(:,j,:)),[24*20,1]))/20;
    err_5(j) = std(reshape(squeeze(ESS_5(:,j,:)),[24*20,1]))/30;
end

%%
ESSmean_2 = squeeze(mean(ESS_2,3))/5;
ESSmean_3= squeeze(mean(ESS_3,3))/15;
ESSmean_4= squeeze(mean(ESS_4,3))/20;
ESSmean_5 = squeeze(mean(ESS_5,3))/30;
% ESSmean_1=mean(ESS_1);
% RSpercent_1 = mean(squeeze(ESS_1),[2]);
% RSpercent_2 = mean(squeeze(RSpercent_2),[2]);

%% Mwan and STD
TOLC=ptc12(12);
figure(1)
tt = tiledlayout(1,2);
nexttile
% plot(numModes,ESSave_1,'Color', TOLC(1,:),'LineStyle','-', 'LineWidth', 1.5)
% % errorbar(numModes,ESSave_1,err_1,'Color', TOLC(1,:), 'LineWidth', 1.5)
% % grid on
% % hold on
errorbar(numModes,ESSave_2,err_2,'Color', TOLC(4,:), 'LineWidth', 1.5)
grid on
hold on
errorbar(numModes,ESSave_3,err_3,'Color', TOLC(9,:), 'LineWidth', 1.5)
errorbar(numModes,ESSave_4,err_4,'Color', TOLC(3,:), 'LineWidth', 1.5)
errorbar(numModes,ESSave_5,err_5,'Color', TOLC(7,:), 'LineWidth', 1.5)
% plot(numModes,ESSave_2,'Color', TOLC(11,:),'LineStyle','-', 'LineWidth', 1.5)
% plot(ESSmean_2(:,8),'Color', TOLC(11,:),'LineStyle',':','LineWidth', 1.5)
% plot(Time(:,1,1),ESSmean_3(:,10),'Color', TOLC(4,:),'LineStyle','--','LineWidth', 1.5)
% h = legend({'L=05','L=20','L=30'});
% h = legend({'L=05','L=15'});
% title(h, 'Number of Particles ')
% yline(0.01, '--', 'Obs.Error','HandleVisibility','off');
% h=legend({'L=05','L=15','L=20','L=30'},...'L=20',
%     'FontWeight','normal',...
%     'FontSize',11,...
%     'FontName','Times',...
%     'Location','Best');
% title(h, 'Number of Particles ',...
%     'FontWeight','normal',...
%     'FontSize',11,...
%     'FontName','Times');
% xlabel('$Time$',...
%     'interpreter','latex',...
%     'FontWeight','normal',...
%     'FontSize',14,...
%     'FontName','Times')
xlabel('$M^q$',...
    'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
ylabel('ESS (mean and std of $20$ trials)',...
    'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
title('Effective Sample Size',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
set(gca,...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
ylim([-0.2 1])
xlim([min(numModes) max(numModes)])
set(gca,'TickLabelInterpreter','latex')
set(gca,'XTick',unique( [get(gca,'XTick'), xlim] ))
hold off
%
nexttile
plot(ESSmean_2(:,6),'Color', TOLC(4,:),'LineStyle','-','LineWidth', 1.5)
grid on
hold on
plot(ESSmean_3(:,6),'Color', TOLC(9,:),'LineStyle','-', 'Marker', 'o','LineWidth', 1.5)
plot(ESSmean_4(:,6),'Color', TOLC(3,:),'LineStyle','--', 'Marker', 'o','LineWidth', 1.5)
plot(ESSmean_5(:,6),'Color', TOLC(7,:),'LineStyle','-.','LineWidth', 1.5)
% plot(Time(:,1,1),ESSmean_3(:,10),'Color', TOLC(4,:),'LineStyle','--','LineWidth', 1.5)
% h = legend({'L=05','L=20','L=30'});
% h = legend({'L=05','L=15'});
% title(h, 'Number of Particles ')
% yline(0.01, '--', 'Obs.Error','HandleVisibility','off');
ylim([-0.2 1])
h=legend({'N=05','N=15','N=20','N=30'},...'L=20',
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times',...
    'Location','Best');
title(h, 'Number of Particles ',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times');
xlabel('Time',...
    'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')

ylabel('ESS (mean of $20$ trials)',...
       'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
title('Effective Sample Size',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
set(gca,...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
xlim([1 max(length(Time))])
set(gca,'TickLabelInterpreter','latex')
set(gca,'XTick',unique( [get(gca,'XTick'), xlim] ))
hold off
sgtitle(['Covariances: $Q = $',num2str(epsQ), '$I$, $R = $', num2str(epsR), '$I$'],...
    'interpreter','latex',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FontName','Times')
tt.TileSpacing = 'compact';
tt.Padding = 'compact';
%%
figure(2)
tt = tiledlayout(1,2);
nexttile

% plot(numModes,RMSEave_1,'Color', TOLC(1,:),'LineStyle',':','LineWidth', 1.5)
% 
% grid on
% hold on
plot(numModes,RMSEave_2,'Color', TOLC(4,:),'LineStyle','-','LineWidth', 1.5)
grid on
hold on
plot(numModes,RMSEave_3,'Color', TOLC(9,:),'LineStyle','-', 'Marker', 'o','LineWidth', 1.5)
plot(numModes,RMSEave_4,'Color', TOLC(3,:),'LineStyle','--','Marker', 'o','LineWidth', 1.5)
plot(numModes,RMSEave_5,'Color', TOLC(7,:),'LineStyle','-.','LineWidth', 1.5)
set(gca,'yscale','log')
yline(0.1, '--', 'Obs.Error','HandleVisibility','off');
h=legend({'N=05','N=15','N=20','N=30'},...'L=20',
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times',...
    'Location','Best');
title(h, 'Number of Particles ',...
    'FontWeight','normal',...
    'FontSize',11,...
    'FontName','Times');

xlabel('$M^q$',...
    'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
ylabel('RMSE (mean of $20$ trials)',...
    'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')

title('RMSE',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
set(gca,...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
xlim([min(numModes) max(numModes)])

ylim([0.002 0.2])
set(gca,...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')

set(gca,'TickLabelInterpreter','latex')
set(gca,'XTick',unique( [get(gca,'XTick'), xlim] ))
hold off
%
nexttile
% % plot(numModes,RSpercent_1,'Color', TOLC(1,:),'LineStyle',':','LineWidth', 1.5)
% % grid on
% % hold on
plot(numModes,RSpercent_2,'Color', TOLC(4,:),'LineStyle','-','LineWidth', 1.5)
grid on
hold on
plot(numModes,RSpercent_3,'Color', TOLC(9,:),'LineStyle','-', 'Marker', 'o','LineWidth', 1.5)
plot(numModes,RSpercent_4,'Color', TOLC(3,:),'LineStyle','--', 'Marker', 'o','LineWidth', 1.5)
plot(numModes,RSpercent_5,'Color', TOLC(7,:),'LineStyle','-.','LineWidth', 1.5)
set(gca,'yscale','log')
xlim([min(numModes) max(numModes)])
% h=legend({'L=05','L=15','L=20','L=30'},...'L=20',
%     'FontWeight','normal',...
%     'FontSize',12,...
%     'FontName','Times',...
%     'Location','Best');
% title(h, 'Number of Particles ',...
%     'FontWeight','normal',...
%     'FontSize',11,...
%     'FontName','Times');
xlabel('$M^q$',...
    'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')

ylabel('Resampling (mean of $20$ trials)',...
    'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
title('Resampling Percent',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
ylim([10 101])
set(gca,...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
set(gca,'TickLabelInterpreter','latex')
set(gca,'XTick',unique( [get(gca,'XTick'), xlim] ))
hold off
sgtitle(['Covariances: $Q = $',num2str(epsQ), '$I$, $R = $', num2str(epsR), '$I$'],...
    'interpreter','latex',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FontName','Times')
tt.TileSpacing = 'compact';
tt.Padding = 'compact';
%%
% TOLC=ptc12(12);
% figure(3)
% plot(ESSmean_2(:,6),'Color', TOLC(4,:),'LineStyle','-','LineWidth', 1.5)
% grid on
% hold on
% plot(ESSmean_3(:,6),'Color', TOLC(9,:),'LineStyle','-', 'Marker', 'o','LineWidth', 1.5)
% plot(ESSmean_4(:,6),'Color', TOLC(3,:),'LineStyle','--', 'Marker', 'o','LineWidth', 1.5)
% plot(ESSmean_5(:,6),'Color', TOLC(7,:),'LineStyle','-.','LineWidth', 1.5)
% % plot(Time(:,1,1),ESSmean_3(:,10),'Color', TOLC(4,:),'LineStyle','--','LineWidth', 1.5)
% % h = legend({'L=05','L=20','L=30'});
% % h = legend({'L=05','L=15'});
% % title(h, 'Number of Particles ')
% % yline(0.01, '--', 'Obs.Error','HandleVisibility','off');
% h=legend({'L=05','L=15','L=20','L=30'},...'L=20',
%     'FontWeight','normal',...
%     'FontSize',12,...
%     'FontName','Times',...
%     'Location','Best');
% title(h, 'Number of Particles ',...
%     'FontWeight','normal',...
%     'FontSize',12,...
%     'FontName','Times');
% xlabel('Time',...
%     'interpreter','latex',...
%     'FontWeight','normal',...
%     'FontSize',14,...
%     'FontName','Times')
% 
% ylabel('ESS (mean of $20$ trials)',...
%        'interpreter','latex',...
%     'FontWeight','normal',...
%     'FontSize',14,...
%     'FontName','Times')
% title('Effective Sample Size',...
%     'FontUnits','points',...
%     'FontWeight','normal',...
%     'FontSize',14,...
%     'FontName','Times')
% set(gca,...
%     'FontUnits','points',...
%     'FontWeight','normal',...
%     'FontSize',14,...
%     'FontName','Times')
% xlim([1 max(length(Time))])
% set(gca,'XTick',unique( [get(gca,'XTick'), xlim] ))
% hold off