clear all; close all; clc;
load('SWE_run_4days.mat');
modeloutput=x_save;
% modeloutput=abs(complex(modeloutput));
L=length(modeloutput(1,:));%number of snapshots
m=length(H(1,:));%y-dimension
n=length(H(:,1));%x-dimension
N_gridpoints=m*n;%each snapshot has x*y-dimensions

u=modeloutput(1:N_gridpoints,:);v=modeloutput(N_gridpoints+1:N_gridpoints*2,:);h=modeloutput((N_gridpoints*2)+1:end,:);
u_save=reshape(u,n,m,L);v_save=reshape(v,n,m,L);h_save=reshape(h,n,m,L);
x_1000km = x.*1e-6;
y_1000km = y.*1e-6;
plot_height_range = [9500 10300];
%%
interval = 6;
% Set this to "true" to save each frame as a png file
plot_frames = false;
% Decide whether to show height in metres or km
if mean(plot_height_range) > 1000
    height_scale = 0.001;
    height_title = 'Height Truth';
    Velocity_title = 'Velocity Field Truth';
else
    height_scale = 1;
    height_title = 'Height Truth';
    Velocity_title = 'Velocity Field Truth';
end
it=60*72;
% Extract the height and velocity components for this frame
h = squeeze(h_save(:,:,it));
u = squeeze(u_save(:,:,it));
v= squeeze(v_save(:,:,it));
%%
figure(1)
tt = tiledlayout(2,1);
hh(1)=nexttile;
qp=quiver(x_1000km(3:interval:end), y_1000km(3:interval:end), ...
    u(3:interval:end, 3:interval:end)',...
    v(3:interval:end, 3:interval:end)');
set(qp,'AutoScale','on', 'AutoScaleFactor', 2,'color',[0 0 0])
hold on
handle = image(x_1000km, y_1000km, (u'+v').*height_scale);
set(handle,'CDataMapping','scaled');
set(gca,'ydir','normal');

ylabel('$y $',...
    'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
colormap(cmocean('thermal'));
colorbar
cbarhandle = colorbar;
caxis([0 0.2]);
axis([0 max(x_1000km) 0 max(y_1000km)]);
xlabel('$x$',...
    'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
set(gca,...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
daspect([1.5 1 1]);
title([Velocity_title],...
    'interpreter','latex',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FontName','Times')
hold off
%%
hh(2)=nexttile;
handle = image(x_1000km, y_1000km, (h'+H').*height_scale);
set(handle,'CDataMapping','scaled');
set(gca,'ydir','normal');
colormap(cmocean('curl'));
%caxis(plot_height_range.*height_scale);
axis([0 max(x_1000km) 0 max(y_1000km)]);
colorbar
caxis([9 11]);
xlabel('$x$',...
    'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
ylabel('$y $',...
    'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
title([height_title],...
    'interpreter','latex',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FontName','Times')
set(gca,...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')