clear all;close all;clc
load('SWE_run_4days.mat');
DataMatrix= x_save;%snapshot matrix
r=10;
Nsteps = size(DataMatrix, 2); % number of columns
VALUE=true;
M = mean(DataMatrix, 2); % 2 = mean across columns
stepVALUE = round( linspace(1, Nsteps, 5) );
out = dmd( DataMatrix, dt, r, 'removemean', VALUE,'step',stepVALUE,'sortbyb', VALUE);

% bM = norm(M);
% Mnormalized = M/bM;
% % manually adding the mean value of data back among the modes
% out.Phi = [Mnormalized(:), out.Phi];
% out.b = [bM; out.b];
% out.omega = [0; out.omega];
% out.lambda = [1; out.lambda];
%%
Omega=out.omega ;
% % unstable_index=real(Omega)>1E-6;%~not stable
% stable_index=real(Omega)<-1E-6;
unstable_index=real(Omega)>0;%~not stable
stable_index=real(Omega)<0;
CC=abs(real(Omega))<1E-6;
fig =figure(2);
plot(real(Omega(unstable_index)),imag(Omega(unstable_index)),'kx')
hold on; grid on;
plot(real(Omega(stable_index)),imag(Omega(stable_index)),'ko')
xlabel(' Re$(\omega_m)$',...
   'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
ylabel('Im$(\omega_m)$',...
   'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
set(gca,...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
hold off
% magnifyOnFigure(fig);
%  404,247,560,420
% 418,180,38,88.99999999999997
% scatter(real(Omega(CC)),imag(Omega(CC)),'r','filled')
%%
Lambda=out.lambda;
figure(3)
scatter(real(Lambda), imag(out.lambda),'filled')
% figure(3)
% scatter(real(Lambda), imag(out.lambda),1+50*abs(out.b(:,1))/max(abs(out.b(:,1))),'filled')
%%
bb=out.b;
Phi=out.Phi(:,stable_index);
figure(4)
plot(imag(out.lambda(1:end)), out.meanL2norm,'ko','LineWidth',0.9)
% plot(imag(out.lambda(2:end)), out.meanL2norm,'ko','LineWidth',0.9)
grid on
set(gca, 'yscale','log')
xlabel(' Im$(\lambda_m)$',...
   'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
ylabel('Mean $L_2$ Norm',...
   'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
set(gca,...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
 hold off
figure(5)
% plot(imag(Lambda(2:end)), abs(out.b(2:end)),'ko','LineWidth',0.9)
plot(imag(Lambda(1:end)), abs(out.b(1:end)),'ko','LineWidth',0.9)
grid on
set(gca, 'yscale','log')
xlabel(' Im$(\lambda_m)$',...
   'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
ylabel('$\left| b_m \right|  $',...
   'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
set(gca,...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
 hold off
 
figure(6)
plot(real(Omega(1:end)), imag(Omega(1:end)),'ko','LineWidth',0.9)
grid on
% set(gca, 'yscale','log')
xlabel(' Im$(\omega_m)$',...
   'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
ylabel('Re$(\omega_m)$',...
   'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
set(gca,...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',14,...
    'FontName','Times')
 hold off
 